### PR TITLE
Add support to cookies

### PR DESCRIPTION
**Pull request by ramosisw**
Support to cookies Auth

### CODE REVIEW

**Comment by ADmad** [comment]
Why?

**Comment by ramosisw** [comment]
For an apps without Js CoreClient

**Comment by ADmad** [comment]
What kind of apps are those and why can't they use headers or query string to pass the token?

**Comment by ramosisw** [comment]
In my app is based on FormAuth, and the AuthHeader isn't easy way... the parameter is more dificult for the app will content many Urls so we will have add the parameter to every path... and the easily way is use cookies with the jwt token.

**Comment by ADmad** [comment]
Why does a web app need URLs which pass credentials for a stateless authenticator? If you can use cookies means you can use session so why not just use regular session based authentication which FormAuth provides?

**Comment by ADmad** [comment]
I still don't fully understand your use case but checking around the net a bit I see support for reading JWT from cookie is also a common thing. So I am okay with this.

Tests needed for the new feature.

**Comment by ramosisw** [comment]
Tests was added

**Comment by ADmad** [comment]
Looks good, just the coding standards errors need to be fixed.
https://travis-ci.org/ADmad/cakephp-jwt-auth/jobs/372918641#L583

**Pull request merged**
